image: node:12.5.0-alpine

stages:
  - lint
  - build
  - docker

lint:
  stage: lint
  script:
    - yarn
    - yarn prettier
    - yarn tslint
    # - yarn tsc-lint

build:
  stage: build
  script:
    - yarn clean
    - yarn
    - yarn build
  artifacts:
    paths:
      - ./dist/
